language: node_js
script:
- cd bin && node generate-readme-from-json.js
after_success:
- bash ../.deploy.sh
env:
  global:
    secure: oYQRm9VgZq4OaTYuOwvupNlCwAUN2EJIbAcprtEwDdYMGhdqJNxKmfWRVaTveaPEPolztm4xYTk7UFeZTTZyJHBRPbf83vlvF3+1CVb2NC1wUBpPlAyuSAHkTS20YdKhjl4GK6rnjjbC5G6B0ZM09cbQ37CKGW843nEuy32QY7yXBi8Q0dTSmVupb9Lur42JgPuBDufBxrSdKaSEGJdpACRE16OB7X4vcLucV3Kb9h6tE2akrbD/dTaluNV88alM9/n+kiCnvQYv5KKzXQ5lUWzX5iyY+mU6V17VP2LsnkUtPGXxPQGaajd3D+ix1ysQeRTc7WpmUjN/ZA3N7cw9vIgF70WjBb9wL/hbd/PDSqjdm3LGWbRSJYs53iJuA5etib6kBOgRhEt/OsYEIDSQfNeqxJcj/cuxANLAQA1EA6/rQ5HBsdmajPUrRRA3O2MHDLEljl7U1SLvFdQCcXkI55Nathvq2gBuZEYOwZMYdgzb8AEgPsKODQ57KIUnCaDo1OEqG/oimGxb5Vdo43s3xHVGVhfwN5kjYiGnLRWACQ1GWT469ECtw+++v5O4uJ68kgPRtUbzLbWO0Hkj/EpNKoogPQ+jRHS/OKzrVrMDlkW8+IvxAeZPgLtncDFc/Fii26no6vgKhmC4PKPk6rGJv6vSly9NSBsZRRMKn4mCSQk=
